#!/bin/bash

read -p "enter name: " name
numbers=('0' '1' '2' '3' '4' '5' '6' '7' '8' '9')

numbers_output=$(echo "${numbers[*]}")



for number in $numbers_output
do
  if [[ "$name" == *"$number"* ]]; then
    echo "err"
    exit 12
  fi
done

echo "name is: $name"

read -p "enter zno: " zno

letters=('a' 'b' 'c' 'd' 'f' 'g' 'h' 'j' 'k' 'l' 'm' 'n' 'p' 'q' 'r' 's' 't' 'v' 'w' 'x' 'y' 'z' 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z' 'А' 'а' 'Б' 'б' 'В' 'в' 'Г' 'г' 'Д' 'д' 'Е' 'е' 'Ё' 'ё' 'Ж' 'ж' 'З' 'з' 'И' 'и' 'Й' 'й' 'К' 'к' 'Л' 'л' 'М' 'м' 'Н' 'н' 'О' 'о' 'П' 'п' 'С' 'с' 'Т' 'т' 'У' 'у' 'Ф' 'ф' 'Х' 'х' 'Ц' 'ц' 'Ч' 'ч' 'Ш' 'ш' 'Щ' 'щ' 'Ъ' 'ъ' 'Ы' 'ы' 'Ь' 'ь' 'Э' 'э' 'Ю' 'ю' 'Я' 'я')
letters_output=$(echo "${letters[*]}")

for letter in $letters_output
do
  if [[ "$zno" == *"$letter"* ]]; then
    echo "error"
    exit 13
  fi
done
echo "zno is: $zno"