#!/bin/bash
COUNT_DISKS_BY_NAMES=$(lsblk -s | awk '/disk/' | sed -s 's/└─//g' | awk '{print $1}' | uniq)

COUNT_SYSTEM_DISKS=$(lsblk -s | awk '/disk/' | sed -s 's/└─//g' | awk '{print $1}' | uniq | wc -l)


if [ $COUNT_SYSTEM_DISKS -gt 1 ]; then #ge
    for item in $COUNT_DISKS_BY_NAMES
    do
        case $item in
            *nv*)
                DISKTYPE="SSD" ;;
            *sd*)
                DISKTYPE1="HDD" ;;
        esac
    done
    k=$(echo -e "$DISKTYPE\n$DISKTYPE1" | wc -l)
    else
        DISKTYPE1="On this PC only 1 disk in system"

 #       echo -e "\n$DISKTYPE1"
fi

if [[ $k -ge 2 ]]; then
    DISKTYPEA=$(echo -e "$DISKTYPE\n$DISKTYPE1"| tail -n 1)
    echo $DISKTYPEA
fi
#cho $COUNT_SYaTEM_DISKS